# Generated by Django 3.1.5 on 2021-09-06 17:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210903_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='favourite_quote',
            field=models.TextField(blank=True, help_text='Favourite Quote', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='favourite_scripture',
            field=models.TextField(blank=True, help_text='Favourite Scripture', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='interests',
            field=models.TextField(blank=True, help_text='Interests', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='job_skill',
            field=models.CharField(blank=True, help_text='Job/Skill', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='ministry',
            field=models.CharField(blank=True, help_text='Ministry', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='place_of_worship',
            field=models.TextField(blank=True, help_text='Place of Worship', max_length=200, null=True),
        ),
    ]
