# Generated by Django 3.1.5 on 2021-09-07 20:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210906_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='birthday',
            field=models.DateTimeField(blank=True, default='-----', null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(help_text='Email', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='favourite_quote',
            field=models.TextField(blank=True, default='-----', help_text='Favourite Quote', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='favourite_scripture',
            field=models.TextField(blank=True, default='-----', help_text='Favourite Scripture', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='full_name',
            field=models.CharField(help_text='Full Name', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='house_address',
            field=models.TextField(blank=True, default='-----', help_text='Home Address', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='interests',
            field=models.TextField(blank=True, default='-----', help_text='Interests', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='job_skill',
            field=models.CharField(blank=True, default='-----', help_text='Job/Skill', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='ministry',
            field=models.CharField(blank=True, default='-----', help_text='Ministry', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='place_of_worship',
            field=models.TextField(blank=True, default='-----', help_text='Place of Worship', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(help_text='Full Name', max_length=80, null=True),
        ),
    ]
