# Generated by Django 3.1.5 on 2021-09-09 22:30

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210907_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(blank=True, default='pro.png', null=True, upload_to='avatars', validators=[blog.validators.avatar_size]),
        ),
        migrations.AlterField(
            model_name='author',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='favourite_quote',
            field=models.TextField(blank=True, help_text='Favourite Quote', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='favourite_scripture',
            field=models.TextField(blank=True, help_text='Favourite Scripture', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='house_address',
            field=models.TextField(blank=True, help_text='Home Address', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='interests',
            field=models.TextField(blank=True, help_text='Interests', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='job_skill',
            field=models.CharField(blank=True, help_text='Job/Skill', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='ministry',
            field=models.CharField(blank=True, help_text='Ministry', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='place_of_worship',
            field=models.TextField(blank=True, help_text='Place of Worship', max_length=1000, null=True),
        ),
    ]
