# Generated by Django 3.1.5 on 2021-09-17 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20210917_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='author_slug',
        ),
    ]
