# Generated by Django 3.1.5 on 2021-09-24 23:58

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20210918_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='news',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='question',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(related_name='posts', to='blog.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='medi',
            field=models.FileField(null=True, upload_to='media', validators=[blog.validators.validate_is_media, blog.validators.media_size]),
        ),
    ]
