# Generated by Django 3.1.5 on 2021-10-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_answer_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='replyanswer',
            options={'verbose_name_plural': 'Answer Replies'},
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
