# Generated by Django 3.1.5 on 2021-10-02 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='from_user',
            new_name='from_author',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='to_user',
            new_name='to_author',
        ),
    ]
