# Generated by Django 3.1.5 on 2021-10-02 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20211002_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user_has_seen',
            new_name='author_has_seen',
        ),
    ]
