# Generated by Django 3.1.5 on 2021-10-05 00:16

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_adminnotifications_terms_and_conditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, null=True)),
                ('text', ckeditor.fields.RichTextField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('mission', ckeditor.fields.RichTextField(null=True)),
                ('vision', ckeditor.fields.RichTextField(null=True)),
                ('core_values', ckeditor.fields.RichTextField(null=True)),
                ('medi', models.FileField(null=True, upload_to='media')),
            ],
            options={
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.AlterModelOptions(
            name='adminnotifications',
            options={'verbose_name_plural': 'Admin Notifications'},
        ),
        migrations.AlterModelOptions(
            name='terms_and_conditions',
            options={'verbose_name_plural': 'Terms & Conditions'},
        ),
        migrations.RenameField(
            model_name='news',
            old_name='media',
            new_name='medi',
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.author')),
            ],
            options={
                'verbose_name_plural': 'Message',
            },
        ),
    ]
