# Generated by Django 3.1.5 on 2021-10-05 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20211005_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='blog.news'),
        ),
    ]
