# Generated by Django 3.1.5 on 2021-10-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20211007_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotifications',
            name='author',
            field=models.ManyToManyField(to='blog.Author'),
        ),
        migrations.AddField(
            model_name='adminnotifications',
            name='url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='adminnotifications',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
