# Generated by Django 3.1.5 on 2021-10-10 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20211010_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='admin_notifications',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.adminnotifications'),
        ),
    ]
