# Generated by Django 3.1.5 on 2021-10-10 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_notification_admin_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='authors',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Author'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='to_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_to', to='blog.author'),
        ),
    ]
