# Generated by Django 3.1.5 on 2021-10-10 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_auto_20211010_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='authors',
        ),
        migrations.AddField(
            model_name='news',
            name='author_has_seen',
            field=models.BooleanField(default=False),
        ),
    ]
