# Generated by Django 3.1.5 on 2021-10-11 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_auto_20211011_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='authors',
            field=models.ManyToManyField(related_name='info', to='blog.Author'),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='blog.author'),
        ),
    ]
