# Generated by Django 3.1.5 on 2021-10-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_auto_20211011_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='text',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
