# Generated by Django 3.1.5 on 2021-10-11 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_auto_20211011_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminnotifications',
            name='author',
        ),
    ]
