# Generated by Django 3.1.5 on 2021-10-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_remove_adminnotifications_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_num',
            field=models.IntegerField(default=2021,),
        ),
       
    ]
