# Generated by Django 3.1.5 on 2021-10-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_auto_20211011_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_num',
            field=models.IntegerField(null=True),
        ),
    ]
