# Generated by Django 3.1.5 on 2021-10-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0044_auto_20211011_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='news_num',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
