# Generated by Django 3.1.5 on 2021-10-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0045_notification_news_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_num',
            field=models.IntegerField(default=2021, unique=True),
        ),
    ]
