# Generated by Django 3.1.5 on 2021-10-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0046_auto_20211011_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='news_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
