# Generated by Django 3.1.5 on 2021-10-11 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0047_auto_20211011_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='author_has_seen',
        ),
        migrations.RemoveField(
            model_name='news',
            name='to_author',
        ),
    ]
