# Generated by Django 3.1.5 on 2021-10-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0053_auto_20211015_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='anonymous_disapproved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='disapproved',
            field=models.ManyToManyField(blank=True, related_name='disapproved_comments', to='blog.Author'),
        ),
        migrations.AddField(
            model_name='reply',
            name='anonymous_disapproved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='disapproved',
            field=models.ManyToManyField(blank=True, related_name='disapproved_replies', to='blog.Author'),
        ),
    ]
