# Generated by Django 3.1.5 on 2021-10-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0054_auto_20211018_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='anonymous_disapproved',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='disapproved',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='anonymous_disapproved',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='disapproved',
        ),
        migrations.AddField(
            model_name='comment',
            name='flagged',
            field=models.ManyToManyField(blank=True, related_name='flagged_comments', to='blog.Author'),
        ),
        migrations.AddField(
            model_name='reply',
            name='flagged',
            field=models.ManyToManyField(blank=True, related_name='flagged_replies', to='blog.Author'),
        ),
    ]
