# Generated by Django 3.2.8 on 2021-11-26 19:39

import blog.validators
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0055_auto_20211019_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community_Standards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, null=True)),
                ('text', ckeditor.fields.RichTextField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Community Standards',
            },
        ),
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.FileField(blank=True, default='pro.png', null=True, upload_to='avatars', validators=[blog.validators.avatar_size]),
        ),
        migrations.AlterField(
            model_name='news',
            name='medi',
            field=models.FileField(blank=True, default='lll.gif', null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='medi',
            field=models.FileField(null=True, upload_to='media', validators=[blog.validators.media_size]),
        ),
    ]
