# Generated by Django 3.2.8 on 2021-11-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0056_auto_20211126_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community_standards',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
