# Generated by Django 3.2.8 on 2021-12-26 21:55

import blog.validators
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0058_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='medi',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='media'),
        ),
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[blog.validators.avatar_size], verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='news',
            name='medi',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[blog.validators.media_size], verbose_name='medi'),
        ),
        migrations.AlterField(
            model_name='post',
            name='medi',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, validators=[blog.validators.media_size], verbose_name='media'),
        ),
    ]
