# Generated by Django 3.2.8 on 2021-12-26 22:35

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0059_auto_20211226_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='medi',
            field=models.FileField(blank=True, null=True, upload_to='about_pic/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='avatars/', validators=[blog.validators.avatar_size, blog.validators.validate_is_pic]),
        ),
        migrations.AlterField(
            model_name='news',
            name='medi',
            field=models.FileField(blank=True, null=True, upload_to='fliers/', validators=[blog.validators.media_size]),
        ),
        migrations.AlterField(
            model_name='post',
            name='medi',
            field=models.FileField(null=True, upload_to='post_pics/', validators=[blog.validators.media_size]),
        ),
    ]
