# Generated by Django 3.2.8 on 2021-12-27 14:38

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0063_auto_20211227_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, default='lll.gif/', null=True, upload_to='post_pics/', validators=[blog.validators.media_size]),
        ),
    ]
