# Generated by Django 3.2.8 on 2021-12-27 23:35

import blog.validators
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0065_alter_post_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='video',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage, upload_to='about_pic/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[blog.validators.avatar_size, blog.validators.validate_is_pic]),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, default='lll.gif/', null=True, upload_to='fliers/', validators=[blog.validators.media_size]),
        ),
        migrations.AlterField(
            model_name='news',
            name='video',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage, upload_to='fliers/', validators=[blog.validators.media_size]),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='lll.gif/', null=True, upload_to='post_pics/', validators=[blog.validators.media_size]),
        ),
    ]
